using Content.Client.Administration.Managers;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls; // Scp added - use control-based tab helpers for SCP tab insertion
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class OptionsMenu : DefaultWindow
    {
        [Dependency] private IClientAdminManager _adminManager = default!;

        public OptionsMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            // Scp edit start - keep tab titles aligned after adding the SCP tab
            TabContainer.SetTabTitle(ScpTab, Loc.GetString("ui-options-tab-scp"));
            TabContainer.SetTabTitle(MiscTab, Loc.GetString("ui-options-tab-misc"));
            TabContainer.SetTabTitle(GraphicsTab, Loc.GetString("ui-options-tab-graphics"));
            TabContainer.SetTabTitle(KeyRebindTab, Loc.GetString("ui-options-tab-controls"));
            TabContainer.SetTabTitle(AudioTab, Loc.GetString("ui-options-tab-audio"));
            TabContainer.SetTabTitle(AccessibilityTab, Loc.GetString("ui-options-tab-accessibility"));
            TabContainer.SetTabTitle(AdminOptionsTab, Loc.GetString("ui-options-tab-admin"));
            // Scp edit end

            UpdateTabs();
        }

        public void UpdateTabs()
        {
            var isAdmin = _adminManager.IsAdmin(true);
            TabContainer.SetTabVisible(AdminOptionsTab, isAdmin); // Scp edit - avoid index drift from fork tabs

            ScpTab.Control.ReloadValues(); // Scp added
            GraphicsTab.Control.ReloadValues();
            MiscTab.Control.ReloadValues();
            AccessibilityTab.Control.ReloadValues();
            AudioTab.Control.ReloadValues();
            AdminOptionsTab.Control.ReloadValues();
        }
    }
}
