using Content.Client.UserInterface.Controls;
using Content.Shared._Scp.Helpers;
using Content.Shared.Research;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class DiskConsoleMenu : FancyWindow
{
    public event Action? OnServerButtonPressed;
    public event Action? OnPrintButtonPressed;

    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public DiskConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        PrintButton.OnPressed += _ => OnPrintButtonPressed?.Invoke();
    }

    public void Update(DiskConsoleBoundUserInterfaceState state)
    {
        PrintButton.Disabled = !state.CanPrint;
        TotalLabel.Text = Loc.GetString("tech-disk-ui-total-label",
            ("amount", ResearchPointsHelper.PointsToString(state.ServerPoints, "  ", _prototype)));
        CostLabel.Text = Loc.GetString("tech-disk-ui-cost-label",
            ("amount", ResearchPointsHelper.PointsToString(state.PointCost, "  ", _prototype)));
    }
}

