using Content.Client._Scp.UI.Stylesheets.Palette;
using Content.Shared.CartridgeLoader;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.PDA;

[GenerateTypedNameReferences]
public sealed partial class PdaProgramItem : ContainerButton
{
    public const string StylePropertyBgColor = "backgroundColor";

    // Scp edit start
    public static readonly string NormalBgColor = ScpPalettes.PanelDarker.ToHex();
    public static readonly string HoverColor = ScpPalettes.LightGray.ToHex();
    // Scp edit end

    private Entity<CartridgeComponent> _cartridge;

    public event Action<EntityUid>? OnProgramItemPressed;
    public event Action<EntityUid>? OnUninstallButtonPressed;
    public event Action<EntityUid>? OnInstallButtonPressed;

    private readonly StyleBoxFlat _styleBox = new()
    {
        BackgroundColor = ScpPalettes.PanelDarker, // Scp edit
    };

    public Color BackgroundColor
    {
        get => _styleBox.BackgroundColor;
        set => _styleBox.BackgroundColor = value;
    }

    public PdaProgramItem(Entity<CartridgeComponent> program)
    {
        RobustXamlLoader.Load(this);

        SetCartridge(program);
        Panel.PanelOverride = _styleBox;

        OnPressed += OnSelfPressed;
        InstallButton.OnPressed += OnInstallPressed;
    }

    private void OnSelfPressed(ButtonEventArgs args)
    {
        OnProgramItemPressed?.Invoke(_cartridge);
    }

    private void OnInstallPressed(ButtonEventArgs args)
    {
        switch (_cartridge.Comp.InstallationStatus)
        {
            case InstallationStatus.Cartridge:
                OnInstallButtonPressed?.Invoke(_cartridge.Owner);
                break;

            case InstallationStatus.Installed:
                OnUninstallButtonPressed?.Invoke(_cartridge.Owner);
                break;

            case InstallationStatus.Readonly:
            default:
                break;
        }
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (TryGetStyleProperty<Color>(StylePropertyBgColor, out var bgColor))
            BackgroundColor = bgColor;
    }

    public void SetCartridge(Entity<CartridgeComponent> program)
    {
        if (program.Comp.Icon is { } icon)
            Icon.SetFromSpriteSpecifier(icon);

        _cartridge = program;
        ProgramName.Text = Loc.GetString(program.Comp.ProgramName);

        switch (program.Comp.InstallationStatus)
        {
            case InstallationStatus.Cartridge:
                InstallButton.Visible = true;
                InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-install-button");
                break;
            case InstallationStatus.Installed:
                InstallButton.Visible = true;
                InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-uninstall-button");
                break;
            case InstallationStatus.Readonly:
                InstallButton.Visible = false;
                break;
        }
    }
}
