# Руководство

- type: playTimeTracker
  id: JobFacilityDirector

- type: playTimeTracker
  id: JobScpResearchDirector

- type: playTimeTracker
  id: JobSecurityCommander

- type: playTimeTracker
  id: JobScpChiefEngineer

- type: playTimeTracker
  id: JobPersonnelManager

- type: playTimeTracker
  id: JobScpChiefMedicalOfficer

- type: playTimeTracker
  id: JobScpQuartermaster

# Комитет по этике

- type: playTimeTracker
  id: JobEthicsCommitteeRepresentative

# Служба безопасности тяжелой зоны

- type: playTimeTracker
  id: JobSpecialPurposeUnitCommander

- type: playTimeTracker
  id: JobSeniorSpecialPurposeSquadOfficer

- type: playTimeTracker
  id: JobSpecialPurposeSquadOfficer

- type: playTimeTracker
  id: JobJuniorSpecialPurposeSquadOfficer

- type: playTimeTracker
  id: JobAmnesticologist

# Комендантский отряд

- type: playTimeTracker
  id: JobCommandantLeader

- type: playTimeTracker
  id: JobSeniorCommandant

- type: playTimeTracker
  id: JobCommandant

- type: playTimeTracker
  id: JobJuniorCommandant

# Научный отдел

- type: playTimeTracker
  id: JobSeniorResearcher

- type: playTimeTracker
  id: JobResearcher

- type: playTimeTracker
  id: JobManufacturingSpecialist

- type: playTimeTracker
  id: JobLaboratoryPractitioner

# Медицинский отдел

- type: playTimeTracker
  id: JobSeniorPhysician

- type: playTimeTracker
  id: JobPharmacist

- type: playTimeTracker
  id: JobPhysician

- type: playTimeTracker
  id: JobParapsychologist

- type: playTimeTracker
  id: JobAssistantPhysician

# Инженерный отдел

- type: playTimeTracker
  id: JobSeniorEngineer

- type: playTimeTracker
  id: JobTechnician

- type: playTimeTracker
  id: JobElectricalEngineer

- type: playTimeTracker
  id: JobTraineeTechnician

# Отдел логистики

- type: playTimeTracker
  id: JobLogistician

# Департамент продовольственного и санитарного обслуживания

- type: playTimeTracker
  id: JobGastronomist

- type: playTimeTracker
  id: JobBotanistPhytogeneticist

- type: playTimeTracker
  id: JobServiceStaff

# Класс Д

- type: playTimeTracker
  id: JobClassD

- type: playTimeTracker
  id: JobClassDCook

- type: playTimeTracker
  id: JobClassDBotanist

- type: playTimeTracker
  id: JobClassDJanitor

# SCP

- type: playTimeTracker
  id: JobScp173

- type: playTimeTracker
  id: JobScp939

- type: playTimeTracker
  id: JobScp049

- type: playTimeTracker
  id: JobScp082

- type: playTimeTracker
  id: JobScp106

- type: playTimeTracker
  id: JobScp096

- type: playTimeTracker
  id: JobScp999

- type: playTimeTracker
  id: JobScp131A

- type: playTimeTracker
  id: JobScp131B
  
- type: playTimeTracker
  id: JobScp2295

# Отряды МОГ

- type: playTimeTracker
  id: JobHDLeader

- type: playTimeTracker
  id: JobHDSpecialist

- type: playTimeTracker
  id: JobHDCadet

- type: playTimeTracker
  id: JobLLHLeader

- type: playTimeTracker
  id: JobLLHSpecialist

- type: playTimeTracker
  id: JobMHLeader

- type: playTimeTracker
  id: JobMHSpecialist

- type: playTimeTracker
  id: JobMHCadet

- type: playTimeTracker
  id: JobRRHLeader

- type: playTimeTracker
  id: JobRRHSpecialist

- type: playTimeTracker
  id: JobNTFLeader

- type: playTimeTracker
  id: JobNTFSpecialist

- type: playTimeTracker
  id: JobNTFCadet

# Служба Безопасности Фонда

- type: playTimeTracker
  id: JobFondSecurityOfficer

- type: playTimeTracker
  id: JobFondSeniorSecurityOfficer

# Антагонисты

- type: playTimeTracker
  id: AntagScp2054X
