- type: job
  id: Logistician
  name: job-name-logistician
  description: job-description-logistician
  playTimeTracker: JobLogistician
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 1h
  - !type:AgeRequirement
    requiredAge: 24
  - !type:AgeRequirement
    requiredAge: 75
    inverted: true
  icon: JobLogistician
  supervisors: job-supervisors-quartermaster
  displayWeight: 0
  weight: 740
  accessGroups:
  - Logistician
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: BoxingDay
    prototype: BoxCardboard
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: One

- type: startingGear
  id: LogisticianGear
  equipment:
    eyes: ClothingEyesGlasses
    neck: ClothingNeckScarfStripedOrange
    outerClothing: ClothingOuterWinterColorOrange
    jumpsuit: ClothingUniformJumpsuitCargo
    gloves: ClothingHandsGlovesColorLightBrown
    shoes: ClothingShoesColorBlack
    back: ClothingBackpackCargo
    id: KeyCardLogistician
    ears: ClothingHeadsetLogistics
    pocket1: AppraisalTool
    pocket2: ScpLogisticsPDA
