- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
  - !type:RoleTimeRequirement
    role: JobScientist
    time: 5h
  - !type:DepartmentTimeRequirement
    department: Science
    time: 10h
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  supervisors: job-supervisors-captain
  canBeAntag: true # Sunrise-Edit
# Scp edit - disabled broken ported content.   radioBold: true # Sunrise-Edit
  displayWeight: 50 # Sunrise-Edit
  overrideConsoleVisibility: false # Fire added
  setPreference: false # Fire added
  # Sunrise-Start
# Scp edit - disabled broken ported content.   alternativeTitles:
#   - job-alt-title-science-lead
  # Sunrise-End
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  - Cryogenics
# Scp edit - disabled broken ported content.   - ResearchConsoleAccess # Sunrise-Edit
  special:
  - !type:AddImplantSpecial
# Scp edit - disabled broken ported content.     implants: [ DeathRattleImplantBlueShield ] # Sunrise-Edit
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
# Scp edit - disabled broken ported content.   speciesBlacklist:
#   - Vox # Sunrise-Edit
#
- type: startingGear
  id: ResearchDirectorGear
  equipment:
    id: RnDPDA
    ears: ClothingHeadsetRD
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: ResearchDirectorChameleonOutfit
  job: ResearchDirector
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretRND
    eyes: ClothingEyesGlasses
    mask: ClothingMaskGas
    neck: ClothingNeckCloakRd
    outerClothing: ClothingOuterCoatRD
    gloves: ClothingHandsGlovesColorPurple
