- type: job
  id: Amnesticologist
  name: job-name-amnesticologist
  description: job-description-amnesticologist
  playTimeTracker: JobAmnesticologist
  requirements:
  - !type:DepartmentTimeRequirement
    department: CommandantSquad
    time: 3h
  - !type:DepartmentTimeRequirement
    department: MedicalService
    time: 3h
  - !type:AgeRequirement
    requiredAge: 29
  - !type:AgeRequirement
    requiredAge: 75
    inverted: true
  icon: JobAmnesticologist
  supervisors: job-supervisors-special-purpose-unit-commander
  displayWeight: 15
  weight: 805
  accessGroups:
  - Amnesticologist
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Three
    - type: ScpHolder
      holdableWhitelist:
        components:
        - HumanoidProfile
      holdableBlacklist:
        components:
        - Scp
    - type: Fear
      phobias:
      - Exoremophobia
      # Врачи не пугаются трупов, у них не будет некрофобии

- type: startingGear
  id: AmnesticologistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    shoes: ClothingShoesColorRed
    back: ClothingBackpackBrigmedic
    gloves: ClothingHandsGlovesLatex
    eyes: ClothingEyesHudMedSec
    id: KeyCardAmnesticologist
    ears: ClothingHeadsetAmnesticologist
    belt: ClothingBeltMedicalFilled
    pocket1: AmnesiacSpray
    pocket2: ScpMedicalPDA
  storage:
    back:
    - Flash
    - ScpRadioHandheldSecurityEnabled
